'use client';

import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { useState } from 'react';

export default function PrivacyPolicyPage() {
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);

  const openModal = (): void => {
    setIsModalOpen(true);
  };

  const closeModal = (): void => {
    setIsModalOpen(false);
  };

  return (
    <>
      <Header onOpenModal={openModal} />
      
      <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-gray-100 pt-32 pb-20">
        <div className="max-w-4xl mx-auto px-6 lg:px-8">
          
          {/* Header */}
          <div className="text-center mb-16">
            <h1 className="text-4xl md:text-5xl font-black text-gray-900 mb-6"
                style={{fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif'}}>
              Privacy Policy
            </h1>
            <div className="flex justify-center mb-8">
              <div className="w-20 h-1 bg-[#FFD580] rounded-full"></div>
            </div>
            <p className="text-lg text-gray-600">
              Effective Date: January 1, 2025
            </p>
          </div>

          {/* Content */}
          <div className="bg-white rounded-3xl shadow-xl p-8 md:p-12 prose prose-lg max-w-none">
            
            <div className="space-y-8">
              
              <section>
                <p className="text-gray-700 leading-relaxed mb-6">
                  Amplified Solutions Consulting LLC ("us", "we", or "our") operates the https://www.amplifiedsolutions.com website (the "Service"). 
                  We specialize in lead management and conversion services for real estate professionals.
                </p>
                
                <p className="text-gray-700 leading-relaxed">
                  This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service 
                  and the choices you have associated with that data. We use your data to provide and improve the Service. By using the Service, 
                  you agree to the collection and use of information in accordance with this policy.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">Definitions</h2>
                
                <div className="space-y-4">
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900 mb-2">Service</h3>
                    <p className="text-gray-700">Service is the https://www.amplifiedsolutions.com website operated by Amplified Solutions Consulting LLC</p>
                  </div>
                  
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900 mb-2">Personal Data</h3>
                    <p className="text-gray-700">Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
                  </div>
                  
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900 mb-2">Usage Data</h3>
                    <p className="text-gray-700">Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                  </div>
                  
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900 mb-2">Cookies</h3>
                    <p className="text-gray-700">Cookies are small pieces of data stored on your device (computer or mobile device).</p>
                  </div>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">Information Collection and Use</h2>
                <p className="text-gray-700 mb-4">
                  We collect several different types of information for various purposes to provide and improve our lead management and conversion services to you.
                </p>
                
                <h3 className="text-lg font-semibold text-gray-900 mb-3">Types of Data Collected</h3>
                
                <div className="mb-6">
                  <h4 className="text-md font-semibold text-gray-900 mb-2">Personal Data</h4>
                  <p className="text-gray-700 mb-3">
                    While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. 
                    Personally identifiable information may include, but is not limited to:
                  </p>
                  <ul className="list-disc pl-6 space-y-1 text-gray-700">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                    <li>Company name and business information</li>
                    <li>Address, State, Province, ZIP/Postal code, City</li>
                    <li>Cookies and Usage Data</li>
                  </ul>
                </div>
                
                <div className="mb-6">
                  <h4 className="text-md font-semibold text-gray-900 mb-2">Usage Data</h4>
                  <p className="text-gray-700">
                    We may also collect information on how the Service is accessed and used. This Usage Data may include information such as your computer's 
                    Internet Protocol address (IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, 
                    the time spent on those pages, unique device identifiers and other diagnostic data.
                  </p>
                </div>
                
                <div>
                  <h4 className="text-md font-semibold text-gray-900 mb-2">Tracking & Cookies Data</h4>
                  <p className="text-gray-700 mb-3">
                    We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.
                  </p>
                  <p className="text-gray-700">
                    You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, 
                    you may not be able to use some portions of our Service.
                  </p>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">Use of Data</h2>
                <p className="text-gray-700 mb-3">
                  Amplified Solutions Consulting LLC uses the collected data for various purposes:
                </p>
                <ul className="list-disc pl-6 space-y-1 text-gray-700">
                  <li>To provide and maintain our lead management and conversion services</li>
                  <li>To notify you about changes to our Service</li>
                  <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                  <li>To provide customer support</li>
                  <li>To gather analysis or valuable information so that we can improve our Service</li>
                  <li>To monitor the usage of our Service</li>
                  <li>To detect, prevent and address technical issues</li>
                  <li>To provide you with news, special offers and general information about other services which we offer that are similar to those that you have already purchased or enquired about</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">Legal Basis for Processing (GDPR)</h2>
                <p className="text-gray-700 mb-3">
                  If you are from the European Economic Area (EEA), our legal basis for collecting and using the personal information described in this 
                  Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.
                </p>
                <p className="text-gray-700 mb-3">
                  We may process your Personal Data because:
                </p>
                <ul className="list-disc pl-6 space-y-1 text-gray-700">
                  <li>We need to perform a contract with you</li>
                  <li>You have given us permission to do so</li>
                  <li>The processing is in our legitimate interests and it's not overridden by your rights</li>
                  <li>For payment processing purposes</li>
                  <li>To comply with the law</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">Data Retention</h2>
                <p className="text-gray-700">
                  We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. 
                  We will retain and use your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, 
                  and enforce our legal agreements and policies.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">Data Security</h2>
                <p className="text-gray-700">
                  The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. 
                  While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">Your Data Protection Rights</h2>
                <p className="text-gray-700 mb-3">
                  If you are a resident of the European Economic Area (EEA), you have certain data protection rights:
                </p>
                <ul className="list-disc pl-6 space-y-1 text-gray-700">
                  <li>The right to access, update or delete the information we have on you</li>
                  <li>The right of rectification</li>
                  <li>The right to object</li>
                  <li>The right of restriction</li>
                  <li>The right to data portability</li>
                  <li>The right to withdraw consent</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">Service Providers</h2>
                <p className="text-gray-700 mb-3">
                  We may employ third party companies and individuals to facilitate our Service. These third parties have access to your Personal Data 
                  only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
                </p>
                
                <div className="space-y-4">
                  <div>
                    <h4 className="text-md font-semibold text-gray-900 mb-2">Analytics</h4>
                    <p className="text-gray-700">
                      We may use Google Analytics to monitor and analyze the use of our Service. You can opt-out of Google Analytics by installing the 
                      Google Analytics opt-out browser add-on.
                    </p>
                  </div>
                  
                  <div>
                    <h4 className="text-md font-semibold text-gray-900 mb-2">Payment Processing</h4>
                    <p className="text-gray-700">
                      We use third-party services for payment processing. We do not store or collect your payment card details. 
                      The payment processors we work with include Stripe and adhere to PCI-DSS standards.
                    </p>
                  </div>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">Children's Privacy</h2>
                <p className="text-gray-700">
                  Our Service does not address anyone under the age of 18. We do not knowingly collect personally identifiable information from anyone under the age of 18. 
                  If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">Changes to This Privacy Policy</h2>
                <p className="text-gray-700">
                  We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and 
                  updating the "effective date" at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">Contact Us</h2>
                <p className="text-gray-700">
                  If you have any questions about this Privacy Policy, please contact us by visiting our contact page at: 
                  <a href="https://www.amplifiedsolutions.com/contact" className="text-[#647b75] hover:underline ml-1">
                    https://www.amplifiedsolutions.com/contact
                  </a>
                </p>
              </section>
              
            </div>
          </div>
        </div>
      </div>
      
      <Footer onOpenModal={openModal} />
    </>
  );
}